%% Function expands base div feature based on stats, worm type, food region, and movie phase.

%% INPUTS:
% logical indices the length of tracking indices. Outputs of
% getWormCategory (5), getFoodRegion (3), and getMoviePhase (4).

%% OUTPUTS:
% featVals: vector of expanded feature values.
% featNames: cell array containing strings of expanded feature names.

% author: serenading. July 2020

function [values, names] = expandDivFeature(singleWormLogInd,multiWormLogInd,clusterLogInd,pausedMwLogInd,tempBlobLogInd,onFoodLogInd,foodEdgeLogInd,offFoodLogInd,phase1LogInd,phase2LogInd,phase3LogInd,notPhase1LogInd)

nInd = numel(tempBlobLogInd);

%% div stats
wormCategoryFractions = [nnz(tempBlobLogInd),nnz(singleWormLogInd),nnz(multiWormLogInd),nnz(clusterLogInd),nnz(pausedMwLogInd)]/nInd;
foodRegionFractions = [nnz(onFoodLogInd),nnz(foodEdgeLogInd),nnz(offFoodLogInd)]/nInd;

%% expand div stats

% worm category & food region
tempBlob_foodRegion = [nnz(tempBlobLogInd & onFoodLogInd),...
    nnz(tempBlobLogInd & foodEdgeLogInd),nnz(tempBlobLogInd & offFoodLogInd)]/nInd;
sw_foodRegion = [nnz(singleWormLogInd & onFoodLogInd),...
    nnz(singleWormLogInd & foodEdgeLogInd),nnz(singleWormLogInd & offFoodLogInd)]/nInd;
mw_foodRegion = [nnz(multiWormLogInd & onFoodLogInd),...
    nnz(multiWormLogInd & foodEdgeLogInd),nnz(multiWormLogInd & offFoodLogInd)]/nInd;
cluster_foodRegion = [nnz(clusterLogInd & onFoodLogInd),...
    nnz(clusterLogInd & foodEdgeLogInd),nnz(clusterLogInd & offFoodLogInd)]/nInd;
pausedMw_foodRegion = [nnz(pausedMwLogInd & onFoodLogInd),...
    nnz(pausedMwLogInd & foodEdgeLogInd),nnz(pausedMwLogInd & offFoodLogInd)]/nInd;

% worm category & movie phase
tempBlob_moviePhase = [nnz(tempBlobLogInd & phase1LogInd),...
    nnz(tempBlobLogInd & phase2LogInd),nnz(tempBlobLogInd & phase3LogInd),nnz(tempBlobLogInd & notPhase1LogInd)]/nInd;
sw_moviePhase = [nnz(singleWormLogInd & phase1LogInd),...
    nnz(singleWormLogInd & phase2LogInd),nnz(singleWormLogInd & phase3LogInd),nnz(singleWormLogInd & notPhase1LogInd)]/nInd;
mw_moviePhase = [nnz(multiWormLogInd & phase1LogInd),...
    nnz(multiWormLogInd & phase2LogInd),nnz(multiWormLogInd & phase3LogInd),nnz(multiWormLogInd & notPhase1LogInd)]/nInd;
cluster_moviePhase = [nnz(clusterLogInd & phase1LogInd),...
    nnz(clusterLogInd & phase2LogInd),nnz(clusterLogInd & phase3LogInd),nnz(clusterLogInd & notPhase1LogInd)]/nInd;
pausedMw_moviePhase = [nnz(pausedMwLogInd & phase1LogInd),...
    nnz(pausedMwLogInd & phase2LogInd),nnz(pausedMwLogInd & phase3LogInd),nnz(pausedMwLogInd & notPhase1LogInd)]/nInd;

% food region & movie phase
onFood_moviePhase = [nnz(onFoodLogInd & phase1LogInd),...
    nnz(onFoodLogInd & phase2LogInd),nnz(onFoodLogInd & phase3LogInd),nnz(onFoodLogInd & notPhase1LogInd)]/nInd;
foodEdge_moviePhase  = [nnz(foodEdgeLogInd & phase1LogInd),...
    nnz(foodEdgeLogInd & phase2LogInd),nnz(foodEdgeLogInd & phase3LogInd),nnz(foodEdgeLogInd & notPhase1LogInd)]/nInd;
offFood_moviePhase  = [nnz(offFoodLogInd & phase1LogInd),...
    nnz(offFoodLogInd & phase2LogInd),nnz(offFoodLogInd & phase3LogInd),nnz(offFoodLogInd & notPhase1LogInd)]/nInd;

% worm category & food region & movie phase
%
tempBlob_foodRegion_phase1 = [nnz(tempBlobLogInd & onFoodLogInd & phase1LogInd),...
    nnz(tempBlobLogInd & foodEdgeLogInd & phase1LogInd),nnz(tempBlobLogInd & offFoodLogInd & phase1LogInd)]/nInd;
tempBlob_foodRegion_phase2 = [nnz(tempBlobLogInd & onFoodLogInd & phase2LogInd),...
    nnz(tempBlobLogInd & foodEdgeLogInd & phase2LogInd),nnz(tempBlobLogInd & offFoodLogInd & phase2LogInd)]/nInd;
tempBlob_foodRegion_phase3 = [nnz(tempBlobLogInd & onFoodLogInd & phase3LogInd),...
    nnz(tempBlobLogInd & foodEdgeLogInd & phase3LogInd),nnz(tempBlobLogInd & offFoodLogInd & phase3LogInd)]/nInd;
tempBlob_foodRegion_notPhase1 = [nnz(tempBlobLogInd & onFoodLogInd & notPhase1LogInd),...
    nnz(tempBlobLogInd & foodEdgeLogInd & notPhase1LogInd),nnz(tempBlobLogInd & offFoodLogInd & notPhase1LogInd)]/nInd;
%
sw_foodRegion_phase1 = [nnz(singleWormLogInd & onFoodLogInd & phase1LogInd),...
    nnz(singleWormLogInd & foodEdgeLogInd & phase1LogInd),nnz(singleWormLogInd & offFoodLogInd & phase1LogInd)]/nInd;
sw_foodRegion_phase2 = [nnz(singleWormLogInd & onFoodLogInd & phase2LogInd),...
    nnz(singleWormLogInd & foodEdgeLogInd & phase2LogInd),nnz(singleWormLogInd & offFoodLogInd & phase2LogInd)]/nInd;
sw_foodRegion_phase3 = [nnz(singleWormLogInd & onFoodLogInd & phase3LogInd),...
    nnz(singleWormLogInd & foodEdgeLogInd & phase3LogInd),nnz(singleWormLogInd & offFoodLogInd & phase3LogInd)]/nInd;
sw_foodRegion_notPhase1 = [nnz(singleWormLogInd & onFoodLogInd & notPhase1LogInd),...
    nnz(singleWormLogInd & foodEdgeLogInd & notPhase1LogInd),nnz(singleWormLogInd & offFoodLogInd & notPhase1LogInd)]/nInd;
%
mw_foodRegion_phase1 = [nnz(multiWormLogInd & onFoodLogInd & phase1LogInd),...
    nnz(multiWormLogInd & foodEdgeLogInd & phase1LogInd),nnz(multiWormLogInd & offFoodLogInd & phase1LogInd)]/nInd;
mw_foodRegion_phase2 = [nnz(multiWormLogInd & onFoodLogInd & phase2LogInd),...
    nnz(multiWormLogInd & foodEdgeLogInd & phase2LogInd),nnz(multiWormLogInd & offFoodLogInd & phase2LogInd)]/nInd;
mw_foodRegion_phase3 = [nnz(multiWormLogInd & onFoodLogInd & phase3LogInd),...
    nnz(multiWormLogInd & foodEdgeLogInd & phase3LogInd),nnz(multiWormLogInd & offFoodLogInd & phase3LogInd)]/nInd;
mw_foodRegion_notPhase1 = [nnz(multiWormLogInd & onFoodLogInd & notPhase1LogInd),...
    nnz(multiWormLogInd & foodEdgeLogInd & notPhase1LogInd),nnz(multiWormLogInd & offFoodLogInd & notPhase1LogInd)]/nInd;
%
cluster_foodRegion_phase1 = [nnz(clusterLogInd & onFoodLogInd & phase1LogInd),...
    nnz(clusterLogInd & foodEdgeLogInd & phase1LogInd),nnz(clusterLogInd & offFoodLogInd & phase1LogInd)]/nInd;
cluster_foodRegion_phase2 = [nnz(clusterLogInd & onFoodLogInd & phase2LogInd),...
    nnz(clusterLogInd & foodEdgeLogInd & phase2LogInd),nnz(clusterLogInd & offFoodLogInd & phase2LogInd)]/nInd;
cluster_foodRegion_phase3 = [nnz(clusterLogInd & onFoodLogInd & phase3LogInd),...
    nnz(clusterLogInd & foodEdgeLogInd & phase3LogInd),nnz(clusterLogInd & offFoodLogInd & phase3LogInd)]/nInd;
cluster_foodRegion_notPhase1 = [nnz(clusterLogInd & onFoodLogInd & notPhase1LogInd),...
    nnz(clusterLogInd & foodEdgeLogInd & notPhase1LogInd),nnz(clusterLogInd & offFoodLogInd & notPhase1LogInd)]/nInd;
%
pausedMw_foodRegion_phase1 = [nnz(pausedMwLogInd & onFoodLogInd & phase1LogInd),...
    nnz(pausedMwLogInd & foodEdgeLogInd & phase1LogInd),nnz(pausedMwLogInd & offFoodLogInd & phase1LogInd)]/nInd;
pausedMw_foodRegion_phase2 = [nnz(pausedMwLogInd & onFoodLogInd & phase2LogInd),...
    nnz(pausedMwLogInd & foodEdgeLogInd & phase2LogInd),nnz(pausedMwLogInd & offFoodLogInd & phase2LogInd)]/nInd;
pausedMw_foodRegion_phase3 = [nnz(pausedMwLogInd & onFoodLogInd & phase3LogInd),...
    nnz(pausedMwLogInd & foodEdgeLogInd & phase3LogInd),nnz(pausedMwLogInd & offFoodLogInd & phase3LogInd)]/nInd;
pausedMw_foodRegion_notPhase1 = [nnz(pausedMwLogInd & onFoodLogInd & notPhase1LogInd),...
    nnz(pausedMwLogInd & foodEdgeLogInd & notPhase1LogInd),nnz(pausedMwLogInd & offFoodLogInd & notPhase1LogInd)]/nInd;

%% collate extracted values into a vector
values = horzcat(wormCategoryFractions,foodRegionFractions,...
tempBlob_foodRegion, sw_foodRegion, mw_foodRegion, cluster_foodRegion, pausedMw_foodRegion,...
tempBlob_moviePhase, sw_moviePhase, mw_moviePhase, cluster_moviePhase, pausedMw_moviePhase,... 
onFood_moviePhase, foodEdge_moviePhase, offFood_moviePhase,...
tempBlob_foodRegion_phase1, tempBlob_foodRegion_phase2, tempBlob_foodRegion_phase3, tempBlob_foodRegion_notPhase1,... 
sw_foodRegion_phase1, sw_foodRegion_phase2, sw_foodRegion_phase3, sw_foodRegion_notPhase1,...
mw_foodRegion_phase1, mw_foodRegion_phase2, mw_foodRegion_phase3, mw_foodRegion_notPhase1,...
cluster_foodRegion_phase1, cluster_foodRegion_phase2, cluster_foodRegion_phase3, cluster_foodRegion_notPhase1,...
pausedMw_foodRegion_phase1, pausedMw_foodRegion_phase2, pausedMw_foodRegion_phase3, pausedMw_foodRegion_notPhase1);

%% collate extracted feature names into a cell array
names = horzcat({'tempBlobFraction'},{'swFraction'},{'mwFraction'},{'clusterFraction'},{'pausedMwFraction'},...
    {'food_region_inside_fraction'},{'food_region_edge_fraction'},{'food_region_outside_fraction'},...
    {'tempBlob_onFood_fraction'},{'tempBlob_foodEdge_fraction'},{'tempBlob_offFood_fraction'},...
    {'sw_onFood_fraction'},{'sw_foodEdge_fraction'},{'sw_offFood_fraction'},...
    {'mw_onFood_fraction'},{'mw_foodEdge_fraction'},{'mw_offFood_fraction'},...
    {'cluster_onFood_fraction'},{'cluster_foodEdge_fraction'},{'cluster_offFood_fraction'},...
    {'pausedMw_onFood_fraction'},{'pausedMw_foodEdge_fraction'},{'pausedMw_offFood_fraction'},...
    {'tempBlob_phase1_fraction'},{'tempBlob_phase2_fraction'},{'tempBlob_phase3_fraction'},{'tempBlob_notPhase1'},...
    {'sw_phase1_fraction'},{'sw_phase2_fraction'},{'sw_phase3_fraction'},{'sw_notPhase1'},...
    {'mw_phase1_fraction'},{'mw_phase2_fraction'},{'mw_phase3_fraction'},{'mw_notPhase1'},...
    {'cluster_phase1_fraction'},{'cluster_phase2_fraction'},{'cluster_phase3_fraction,'},{'cluster_notPhase1'},...
    {'pausedMw_phase1_fraction'},{'pausedMw_phase2_fraction'},{'pausedMw_phase3_fraction'},{'pausedMw_notPhase1'},...
    {'onFood_phase1_fraction'},{'onFood_phase2_fraction'},{'onFood_phase3_fraction'},{'onFood_notPhase1'},...
    {'foodEdge_phase1_fraction'},{'foodEdge_phase2_fraction'},{'foodEdge_phase3_fraction'},{'foodEdge_notPhase1'},...
    {'offFood_phase1_fraction'},{'offFood_phase2_fraction'},{'offFood_phase3_fraction'},{'offFood_notPhase1'},...
    {'tempBlob_onFood_phase1_fraction'},{'tempBlob_foodEdge_phase1_fraction'},{'tempBlob_offFood_phase1_fraction'},...
    {'tempBlob_onFood_phase2_fraction'},{'tempBlob_foodEdge_phase2_fraction'},{'tempBlob_offFood_phase2_fraction'},...
    {'tempBlob_onFood_phase3_fraction'},{'tempBlob_foodEdge_phase3_fraction'},{'tempBlob_offFood_phase3_fraction'},...
    {'tempBlob_onFood_notPhase1_fraction'},{'tempBlob_foodEdge_notPhase1_fraction'},{'tempBlob_offFood_notPhase1_fraction'},...
    {'sw_onFood_phase1_fraction'},{'sw_foodEdge_phase1_fraction'},{'sw_offFood_phase1_fraction'},...
    {'sw_onFood_phase2_fraction'},{'sw_foodEdge_phase2_fraction'},{'sw_offFood_phase2_fraction'},...
    {'sw_onFood_phase3_fraction'},{'sw_foodEdge_phase3_fraction'},{'sw_offFood_phase3_fraction'},...
    {'sw_onFood_notPhase1_fraction'},{'sw_foodEdge_notPhase1_fraction'},{'sw_offFood_notPhase1_fraction'},...
    {'mw_onFood_phase1_fraction'},{'mw_foodEdge_phase1_fraction'},{'mw_offFood_phase1_fraction'},...
    {'mw_onFood_phase2_fraction'},{'mw_foodEdge_phase2_fraction'},{'mw_offFood_phase2_fraction'},...
    {'mw_onFood_phase3_fraction'},{'mw_foodEdge_phase3_fraction'},{'mw_offFood_phase3_fraction'},...
    {'mw_onFood_notPhase1_fraction'},{'mw_foodEdge_notPhase1_fraction'},{'mw_offFood_notPhase1_fraction'},...
    {'cluster_onFood_phase1_fraction'},{'cluster_foodEdge_phase1_fraction'},{'cluster_offFood_phase1_fraction'},...
    {'cluster_onFood_phase2_fraction'},{'cluster_foodEdge_phase2_fraction'},{'cluster_offFood_phase2_fraction'},...
    {'cluster_onFood_phase3_fraction'},{'cluster_foodEdge_phase3_fraction'},{'cluster_offFood_phase3_fraction'},...
    {'cluster_onFood_notPhase1_fraction'},{'cluster_foodEdge_notPhase1_fraction'},{'cluster_offFood_notPhase1_fraction'},...
    {'pausedMw_onFood_phase1_fraction'},{'pausedMw_foodEdge_phase1_fraction'},{'pausedMw_offFood_phase1_fraction'},...
    {'pausedMw_onFood_phase2_fraction'},{'pausedMw_foodEdge_phase2_fraction'},{'pausedMw_offFood_phase2_fraction'},...
    {'pausedMw_onFood_phase3_fraction'},{'pausedMw_foodEdge_phase3_fraction'},{'pausedMw_offFood_phase3_fraction'},...
    {'pausedMw_onFood_notPhase1_fraction'},{'pausedMw_foodEdge_notPhase1_fraction'},{'pausedMw_offFood_notPhase1_fraction'});

assert(numel(values) == numel(names));

end