%% Function expands base feature based on stats, worm type, and movie phase.

%% INPUTS:
% feature: numeric feature vector.
% featureBaseName: string of the feature name.

%% OUTPUTS:
% featVals: vector of expanded feature values.
% featNames: cell array containing strings of expanded feature names.

% author: serenading. June 2020

function [featVals, featNames] = expandFeature(feature,featureBaseName,singleWormLogInd,multiWormLogInd,clusterLogInd,pausedMwLogInd,phase1LogInd,phase2LogInd,phase3LogInd,notPhase1LogInd)


%% get stats
[feature_10th, feature_50th, feature_90th, feature_IQR] = getstats(feature);

%% expand based on worm category
feature_sw = feature(singleWormLogInd);
feature_mw = feature(multiWormLogInd);
feature_cluster = feature(clusterLogInd);
feature_pausedmw = feature(pausedMwLogInd);
%
[feature_sw_10th,feature_sw_50th,feature_sw_90th,feature_sw_IQR] = getstats(feature_sw);
[feature_mw_10th,feature_mw_50th,feature_mw_90th,feature_mw_IQR] = getstats(feature_mw);
[feature_cluster_10th,feature_cluster_50th,feature_cluster_90th,feature_cluster_IQR] = getstats(feature_cluster);
[feature_pausedmw_10th,feature_pausedmw_50th,feature_pausedmw_90th,feature_pausedmw_IQR] = getstats(feature_pausedmw);

%% expand based on movie segment
feature_phase1 = feature(phase1LogInd);
feature_phase2 = feature(phase2LogInd);
feature_phase3 = feature(phase3LogInd);
feature_notphase1 = feature(notPhase1LogInd);
%
[feature_phase1_10th,feature_phase1_50th,feature_phase1_90th,feature_phase1_IQR] = getstats(feature_phase1);
[feature_phase2_10th,feature_phase2_50th,feature_phase2_90th,feature_phase2_IQR] = getstats(feature_phase2);
[feature_phase3_10th,feature_phase3_50th,feature_phase3_90th,feature_phase3_IQR] = getstats(feature_phase3);
[feature_notphase1_10th,feature_notphase1_50th,feature_notphase1_90th,feature_notphase1_IQR] = getstats(feature_notphase1);

%% expand based on movie segment & worm category
feature_sw_phase1 = feature(singleWormLogInd & phase1LogInd);
feature_sw_phase2 = feature(singleWormLogInd & phase2LogInd);
feature_sw_phase3 = feature(singleWormLogInd & phase3LogInd);
feature_sw_notphase1 = feature(singleWormLogInd & notPhase1LogInd);
%
feature_mw_phase1 = feature(multiWormLogInd & phase1LogInd);
feature_mw_phase2 = feature(multiWormLogInd & phase2LogInd);
feature_mw_phase3 = feature(multiWormLogInd & phase3LogInd);
feature_mw_notphase1 = feature(multiWormLogInd & notPhase1LogInd);
%
feature_cluster_phase1 = feature(clusterLogInd & phase1LogInd);
feature_cluster_phase2 = feature(clusterLogInd & phase2LogInd);
feature_cluster_phase3 = feature(clusterLogInd & phase3LogInd);
feature_cluster_notphase1 = feature(clusterLogInd & notPhase1LogInd);
%
feature_pausedmw_phase1 = feature(pausedMwLogInd & phase1LogInd);
feature_pausedmw_phase2 = feature(pausedMwLogInd & phase2LogInd);
feature_pausedmw_phase3 = feature(pausedMwLogInd & phase3LogInd);
feature_pausedmw_notphase1 = feature(pausedMwLogInd & notPhase1LogInd);
%
[feature_sw_phase1_10th,feature_sw_phase1_50th,feature_sw_phase1_90th,feature_sw_phase1_IQR] = getstats(feature_sw_phase1);
[feature_sw_phase2_10th,feature_sw_phase2_50th,feature_sw_phase2_90th,feature_sw_phase2_IQR] = getstats(feature_sw_phase2);
[feature_sw_phase3_10th,feature_sw_phase3_50th,feature_sw_phase3_90th,feature_sw_phase3_IQR] = getstats(feature_sw_phase3);
[feature_sw_notphase1_10th,feature_sw_notphase1_50th,feature_sw_notphase1_90th,feature_sw_notphase1_IQR] = getstats(feature_sw_notphase1);
%
[feature_mw_phase1_10th,feature_mw_phase1_50th,feature_mw_phase1_90th,feature_mw_phase1_IQR] = getstats(feature_mw_phase1);
[feature_mw_phase2_10th,feature_mw_phase2_50th,feature_mw_phase2_90th,feature_mw_phase2_IQR] = getstats(feature_mw_phase2);
[feature_mw_phase3_10th,feature_mw_phase3_50th,feature_mw_phase3_90th,feature_mw_phase3_IQR] = getstats(feature_mw_phase3);
[feature_mw_notphase1_10th,feature_mw_notphase1_50th,feature_mw_notphase1_90th,feature_mw_notphase1_IQR] = getstats(feature_mw_notphase1);
%
[feature_cluster_phase1_10th,feature_cluster_phase1_50th,feature_cluster_phase1_90th,feature_cluster_phase1_IQR] = getstats(feature_cluster_phase1);
[feature_cluster_phase2_10th,feature_cluster_phase2_50th,feature_cluster_phase2_90th,feature_cluster_phase2_IQR] = getstats(feature_cluster_phase2);
[feature_cluster_phase3_10th,feature_cluster_phase3_50th,feature_cluster_phase3_90th,feature_cluster_phase3_IQR] = getstats(feature_cluster_phase3);
[feature_cluster_notphase1_10th,feature_cluster_notphase1_50th,feature_cluster_notphase1_90th,feature_cluster_notphase1_IQR] = getstats(feature_cluster_notphase1);
%
[feature_pausedmw_phase1_10th,feature_pausedmw_phase1_50th,feature_pausedmw_phase1_90th,feature_pausedmw_phase1_IQR] = getstats(feature_pausedmw_phase1);
[feature_pausedmw_phase2_10th,feature_pausedmw_phase2_50th,feature_pausedmw_phase2_90th,feature_pausedmw_phase2_IQR] = getstats(feature_pausedmw_phase2);
[feature_pausedmw_phase3_10th,feature_pausedmw_phase3_50th,feature_pausedmw_phase3_90th,feature_pausedmw_phase3_IQR] = getstats(feature_pausedmw_phase3);
[feature_pausedmw_notphase1_10th,feature_pausedmw_notphase1_50th,feature_pausedmw_notphase1_90th,feature_pausedmw_notphase1_IQR] = getstats(feature_pausedmw_notphase1);

%% collate extracted values into a vector

featVals = horzcat(feature_10th, feature_50th, feature_90th, feature_IQR,...
    feature_sw_10th,feature_sw_50th,feature_sw_90th,feature_sw_IQR,...
    feature_mw_10th,feature_mw_50th,feature_mw_90th,feature_mw_IQR,...
    feature_cluster_10th,feature_cluster_50th,feature_cluster_90th,feature_cluster_IQR,...
    feature_pausedmw_10th,feature_pausedmw_50th,feature_pausedmw_90th,feature_pausedmw_IQR,...
    feature_phase1_10th,feature_phase1_50th,feature_phase1_90th,feature_phase1_IQR,...
    feature_phase2_10th,feature_phase2_50th,feature_phase2_90th,feature_phase2_IQR,...
    feature_phase3_10th,feature_phase3_50th,feature_phase3_90th,feature_phase3_IQR,...
    feature_notphase1_10th,feature_notphase1_50th,feature_notphase1_90th,feature_notphase1_IQR,...
    feature_sw_phase1_10th,feature_sw_phase1_50th,feature_sw_phase1_90th,feature_sw_phase1_IQR,...
    feature_sw_phase2_10th,feature_sw_phase2_50th,feature_sw_phase2_90th,feature_sw_phase2_IQR,...
    feature_sw_phase3_10th,feature_sw_phase3_50th,feature_sw_phase3_90th,feature_sw_phase3_IQR,...
    feature_sw_notphase1_10th,feature_sw_notphase1_50th,feature_sw_notphase1_90th,feature_sw_notphase1_IQR,...
    feature_mw_phase1_10th,feature_mw_phase1_50th,feature_mw_phase1_90th,feature_mw_phase1_IQR,...
    feature_mw_phase2_10th,feature_mw_phase2_50th,feature_mw_phase2_90th,feature_mw_phase2_IQR,...
    feature_mw_phase3_10th,feature_mw_phase3_50th,feature_mw_phase3_90th,feature_mw_phase3_IQR,...
    feature_mw_notphase1_10th,feature_mw_notphase1_50th,feature_mw_notphase1_90th,feature_mw_notphase1_IQR,...
    feature_cluster_phase1_10th,feature_cluster_phase1_50th,feature_cluster_phase1_90th,feature_cluster_phase1_IQR,...
    feature_cluster_phase2_10th,feature_cluster_phase2_50th,feature_cluster_phase2_90th,feature_cluster_phase2_IQR,...
    feature_cluster_phase3_10th,feature_cluster_phase3_50th,feature_cluster_phase3_90th,feature_cluster_phase3_IQR,...
    feature_cluster_notphase1_10th,feature_cluster_notphase1_50th,feature_cluster_notphase1_90th,feature_cluster_notphase1_IQR,...
    feature_pausedmw_phase1_10th,feature_pausedmw_phase1_50th,feature_pausedmw_phase1_90th,feature_pausedmw_phase1_IQR,...
    feature_pausedmw_phase2_10th,feature_pausedmw_phase2_50th,feature_pausedmw_phase2_90th,feature_pausedmw_phase2_IQR,...
    feature_pausedmw_phase3_10th,feature_pausedmw_phase3_50th,feature_pausedmw_phase3_90th,feature_pausedmw_phase3_IQR,...
    feature_pausedmw_notphase1_10th,feature_pausedmw_notphase1_50th,feature_pausedmw_notphase1_90th,feature_pausedmw_notphase1_IQR);

%% collate extracted feature names into a cell array

featNames = horzcat({[featureBaseName, '_10th']}, {[featureBaseName, '_50th']}, {[featureBaseName, '_90th']}, {[featureBaseName, '_IQR']},...
    {[featureBaseName, '_sw_10th']}, {[featureBaseName, '_sw_50th']}, {[featureBaseName, '_sw_90th']}, {[featureBaseName, '_sw_IQR']},...
    {[featureBaseName, '_mw_10th']}, {[featureBaseName, '_mw_50th']}, {[featureBaseName, '_mw_90th']}, {[featureBaseName, '_mw_IQR']},...
    {[featureBaseName, '_cluster_10th']}, {[featureBaseName, '_cluster_50th']}, {[featureBaseName, '_cluster_90th']}, {[featureBaseName, '_cluster_IQR']},...
    {[featureBaseName, '_pausedmw_10th']}, {[featureBaseName, '_pausedmw_50th']}, {[featureBaseName, '_pausedmw_90th']}, {[featureBaseName, '_pausedmw_IQR']},...
    {[featureBaseName, '_phase1_10th']}, {[featureBaseName, '_phase1_50th']}, {[featureBaseName, '_phase1_90th']}, {[featureBaseName, '_phase1_IQR']},...
    {[featureBaseName, '_phase2_10th']}, {[featureBaseName, '_phase2_50th']}, {[featureBaseName, '_phase2_90th']}, {[featureBaseName, '_phase2_IQR']},...
    {[featureBaseName, '_phase3_10th']}, {[featureBaseName, '_phase3_50th']}, {[featureBaseName, '_phase3_90th']}, {[featureBaseName, '_phase3_IQR']},...
    {[featureBaseName, '_notphase1_10th']}, {[featureBaseName, '_notphase1_50th']}, {[featureBaseName, '_notphase1_90th']}, {[featureBaseName, '_notphase1_IQR']},...
    {[featureBaseName, '_sw_phase1_10th']}, {[featureBaseName, '_sw_phase1_50th']}, {[featureBaseName, '_sw_phase1_90th']}, {[featureBaseName, '_sw_phase1_IQR']},...
    {[featureBaseName, '_sw_phase2_10th']}, {[featureBaseName, '_sw_phase2_50th']}, {[featureBaseName, '_sw_phase2_90th']}, {[featureBaseName, '_sw_phase2_IQR']},...
    {[featureBaseName, '_sw_phase3_10th']}, {[featureBaseName, '_sw_phase3_50th']}, {[featureBaseName, '_sw_phase3_90th']}, {[featureBaseName, '_sw_phase3_IQR']},...
    {[featureBaseName, '_sw_notphase1_10th']}, {[featureBaseName, '_sw_notphase1_50th']}, {[featureBaseName, '_sw_notphase1_90th']}, {[featureBaseName, '_sw_notphase1_IQR']},...
    {[featureBaseName, '_mw_phase1_10th']}, {[featureBaseName, '_mw_phase1_50th']}, {[featureBaseName, '_mw_phase1_90th']}, {[featureBaseName, '_mw_phase1_IQR']},...
    {[featureBaseName, '_mw_phase2_10th']}, {[featureBaseName, '_mw_phase2_50th']}, {[featureBaseName, '_mw_phase2_90th']}, {[featureBaseName, '_mw_phase2_IQR']},...
    {[featureBaseName, '_mw_phase3_10th']}, {[featureBaseName, '_mw_phase3_50th']}, {[featureBaseName, '_mw_phase3_90th']}, {[featureBaseName, '_mw_phase3_IQR']},...
    {[featureBaseName, '_mw_notphase1_10th']}, {[featureBaseName, '_mw_notphase1_50th']}, {[featureBaseName, '_mw_notphase1_90th']}, {[featureBaseName, '_mw_notphase1_IQR']},...
    {[featureBaseName, '_cluster_phase1_10th']}, {[featureBaseName, '_cluster_phase1_50th']}, {[featureBaseName, '_cluster_phase1_90th']}, {[featureBaseName, '_cluster_phase1_IQR']},...
    {[featureBaseName, '_cluster_phase2_10th']}, {[featureBaseName, '_cluster_phase2_50th']}, {[featureBaseName, '_cluster_phase2_90th']}, {[featureBaseName, '_cluster_phase2_IQR']},...
    {[featureBaseName, '_cluster_phase3_10th']}, {[featureBaseName, '_cluster_phase3_50th']}, {[featureBaseName, '_cluster_phase3_90th']}, {[featureBaseName, '_cluster_phase3_IQR']},...
    {[featureBaseName, '_cluster_notphase1_10th']}, {[featureBaseName, '_cluster_notphase1_50th']}, {[featureBaseName, '_cluster_notphase1_90th']}, {[featureBaseName, '_cluster_notphase1_IQR']},...
    {[featureBaseName, '_pausedmw_phase1_10th']}, {[featureBaseName, '_pausedmw_phase1_50th']}, {[featureBaseName, '_pausedmw_phase1_90th']}, {[featureBaseName, '_pausedmw_phase1_IQR']},...
    {[featureBaseName, '_pausedmw_phase2_10th']}, {[featureBaseName, '_pausedmw_phase2_50th']}, {[featureBaseName, '_pausedmw_phase2_90th']}, {[featureBaseName, '_pausedmw_phase2_IQR']},...
    {[featureBaseName, '_pausedmw_phase3_10th']}, {[featureBaseName, '_pausedmw_phase3_50th']}, {[featureBaseName, '_pausedmw_phase3_90th']}, {[featureBaseName, '_pausedmw_phase3_IQR']},...
    {[featureBaseName, '_pausedmw_notphase1_10th']}, {[featureBaseName, '_pausedmw_notphase1_50th']}, {[featureBaseName, '_pausedmw_notphase1_90th']}, {[featureBaseName, '_pausedmw_notphase1_IQR']});

end
%% Local function: extracts 10th, 50, 90th percentile and interquartile range of a given feature

function [feature_10th, feature_50th, feature_90th, feature_IQR] = getstats(feature)
feature_10th = prctile(feature,10);
feature_50th = prctile(feature,50);
feature_90th = prctile(feature,90);
feature_IQR = iqr(feature);
end