%% Function finds which 40 worm files are on which HD and appends the information to featureTable under "onHD1" heading. 
% Author: @serenading. July 2020. 

% INPUTS:
% wormNum: 40 or 5.
% extractStamp: of featureTable.
% whichHD: Scalar. Specify 1 or 2. Specify 0 if both 1 and 2 are plugged in.

% OUTPUTS:
% featureTable: skeletal featureTable as generated by generateFeatSummary.
% fileInd: indices for files that are present on the hard drive that is currently plugged in. 

function [featureTable,fileInd] = extractHDLocation(wormNum,extractStamp,whichHD)

if wormNum == 40
    % get feature table filename
    featureTable = readtable(['/Users/sding/OneDrive - Imperial College London/aggScreening/results/fortyWorm/fortyWormFeaturesTable_' extractStamp '.csv'],'Delimiter',',','preserveVariableNames',true);
    % load divergent strain names (these are copied onto HD1, the rest onto HD2)
    load('strainsList/divergent.mat','strains');
    % initialise onHD1 variable to say if the file is on HD1
    onHD1 = false(size(featureTable,1),1);
    % go through the divergent strains to set their onHD1 status to true
    for strainCtr = 1:numel(strains)
        strain = strains{strainCtr};
        strainLogInd = strcmp(featureTable.strain_name,strain);
        onHD1(strainLogInd) = true;
    end
    % append onHD1 variable to featureTable
    featureTable.onHD1 = onHD1;
    
    % Go through each file that is present on this HD to extract features
    if whichHD ==1
        fileInd = find(featureTable.onHD1);
    elseif whichHD ==2
        fileInd = find(~featureTable.onHD1);
    elseif whichHD ==0 % both HDs plugged in
        fileInd = 1:numel(featureTable.onHD1);
    end
    
elseif wormNum ==5
    % all files are on HD1
    assert(whichHD == 1, ['HD' num2str(whichHD) ' is plugged in, but all five worm data are on HD1.']);
    featureTable = readtable(['/Users/sding/OneDrive - Imperial College London/aggScreening/results/fiveWorm/fiveWormFeaturesTable_' extractStamp '.csv'],'Delimiter',',','preserveVariableNames',true);
    fileInd = 1:size(featureTable,1);
end

end