%% This script uses three files to generate a features summary table for the 5 worm aggregation dataset.
% 1. Manually curated metadata file; 2. Filenames file generated by Tierpsy; 3. Features summary file generated by Tierpsy.
% author: serenading. May 2020

clear 
close all

%% set which feature extraction timestamp to use
featExtractTimestamp = '20191024_122847'; %'20191024_122847' or '20181203_141111'

%% Import features data and combine with metadata

% load features matrix, correspondong filenames, and metadata
tierpsyFeatureTable = readtable(['/Users/sding/Desktop/AggregationScreening/features_summary_tierpsy_plate_' featExtractTimestamp '.csv'],'Delimiter',',','preserveVariableNames',true);
tierpsyFileTable = readtable(['/Users/sding/Desktop/AggregationScreening/filenames_summary_tierpsy_plate_' featExtractTimestamp '.csv'],'Delimiter',',','preserveVariableNames',true);
metadataTable = readtable('/Users/sding/Desktop/AggregationScreening/metadata_aggregationScreening.csv','Delimiter',',');

% % trim the metadata table with only useful information for this script
% cols2keep = [find(strcmp(metadataTable.Properties.VariableNames,'basename')),...
%     find(strcmp(metadataTable.Properties.VariableNames,'strain_name')),...
%     find(strcmp(metadataTable.Properties.VariableNames,'wormNum')),...
%     find(strcmp(metadataTable.Properties.VariableNames,'is_bad'))];
% metadataTable = metadataTable(:,cols2keep);

% join the Tierpsy tables to match filenames with file_id. Required in case
% features were not extracted for any files.
combinedTierpsyTable = outerjoin(tierpsyFileTable,tierpsyFeatureTable,'MergeKeys',true);

% get just the filenames from the full path in the combined Tierpsy table
[~, fileNamesTierpsy] = cellfun(@fileparts, combinedTierpsyTable.file_name, 'UniformOutput', false);
combinedTierpsyTable.file_name = strrep(fileNamesTierpsy,'_featuresN','.hdf5');

% rename Tierpsy output and metadata column heads to match
combinedTierpsyTable.Properties.VariableNames{'file_name'} = 'filename';
metadataTable.Properties.VariableNames{'basename'} = 'filename';
   
% finally, join tables to get strain names for each set of features
featureTable = outerjoin(metadataTable,combinedTierpsyTable,'MergeKeys',true);

%% Get five worm features table

% trim the featureTable for 5 worm files
fiveWormLogInd = featureTable.wormNum==5 & featureTable.is_bad==0 & strcmp(featureTable.is_good,'True');
featureTable = featureTable(fiveWormLogInd,:);

% sort featureTable by strain name
strainNameColIdx = find(strcmp(featureTable.Properties.VariableNames,'strain_name'));
featureTable = sortrows(featureTable,strainNameColIdx);

%% export features table
writetable(featureTable,['/Users/sding/Desktop/AggregationScreening/fiveWormFeaturesTable_' featExtractTimestamp '.csv']);